name: Try env feature
# on: push
on: workflow_dispatch
env:
  GLOBAL: Global env !
jobs:
  show-global:
    runs-on: ubuntu-latest
    steps:
      - name: Print Global
        run: echo ${{ env.GLOBAL }}
  show-local:
    needs: show-global
    runs-on: ubuntu-latest
    env:
      LOCAL: Local env here!
    steps:
      - name: Print Local
        run: echo ${{ env.LOCAL }}
